### ISSUE TITLE
TypeError: React.useState is not a function

### ISSUE THREAD

**Issue by MarinAngelo** [lessmess-dev/react-media-hook#2]
node_modules/react-media-hook/index.js:23
  20 | }
  21 | 
  22 | function useMedia(query) {
> 23 |   var result = React.useState(function () {
  24 |     return omitMatchMediaResult(fallbackMathMedia(query));
  25 |   });
  26 |   var setResult = result[1];

useMediaPredicate
node_modules/react-media-hook/index.js:42
  39 | }
  40 | 
  41 | function useMediaPredicate(query) {
> 42 |   var result = useMedia(query);
  43 |   return result && result.matches || false;
  44 | }
  45 |

**Comment by ilyalesik** [comment]
Hi, @MarinAngelo! Installed `react` >= 16.8.0 needed. Are you have it?
